version: '3.8'

services:
  memory-graph:
    build:
      context: .
      dockerfile: Dockerfile
    image: memory-graph:local
    volumes:
      - /home/aaron/Documents/memory-graph-mcp:/app/data
    environment:
      - MEMORY_DIR=/app/data
      - STORAGE_TYPE=sqlite
      - TRANSPORT_TYPE=HTTP
      - PORT=3000
      - HOST=127.0.0.1  # Internal network binding only
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
